Default: &defaults
  database: yesodBlog.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesodBlog_test.sqlite3
  <<: *defaults

Staging:
  database: yesodBlog_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesodBlog_production.sqlite3
  poolsize: 100
  <<: *defaults
